package jwks

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

// TestSignVerify_Roundtrip ensures EdDSA-signed tokens decode against
// the same keystore. Catches signer/verifier drift.
func TestSignVerify_Roundtrip(t *testing.T) {
	ks, err := New("", nil)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	tok, err := ks.Sign("user-42", "user", "leetrank", 5*time.Minute)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}
	claims, err := ks.Verify(tok, "leetrank")
	if err != nil {
		t.Fatalf("Verify: %v", err)
	}
	if claims.Subject != "user-42" {
		t.Errorf("sub = %q, want user-42", claims.Subject)
	}
	if claims.Role != "user" {
		t.Errorf("role = %q, want user", claims.Role)
	}
}

// TestVerify_RejectsBadAudience prevents token reuse across audiences.
func TestVerify_RejectsBadAudience(t *testing.T) {
	ks, _ := New("", nil)
	tok, _ := ks.Sign("u", "user", "leetrank", time.Minute)
	if _, err := ks.Verify(tok, "leetrank-admin"); err == nil {
		t.Fatal("expected audience error, got nil")
	}
}

// TestVerify_RejectsExpired ensures expired tokens are rejected.
// Uses -10m so the default 1-minute leeway in go-jose still treats
// the token as expired.
func TestVerify_RejectsExpired(t *testing.T) {
	ks, _ := New("", nil)
	tok, _ := ks.Sign("u", "user", "leetrank", -10*time.Minute)
	if _, err := ks.Verify(tok, "leetrank"); err == nil {
		t.Fatal("expected expiry error, got nil")
	}
}

// TestJWKSHandler_ShapeMatchesPublicKey verifies the published JWK
// matches the in-memory verifier so external services (problems-go,
// submissions-go) decode the same tokens.
func TestJWKSHandler_ShapeMatchesPublicKey(t *testing.T) {
	ks, _ := New("", nil)
	rec := httptest.NewRecorder()
	ks.JWKSHandler(rec, httptest.NewRequest("GET", "/.well-known/jwks.json", nil))
	if rec.Code != 200 {
		t.Fatalf("status = %d", rec.Code)
	}
	if ct := rec.Header().Get("Content-Type"); !strings.HasPrefix(ct, "application/json") {
		t.Fatalf("ct = %q", ct)
	}
	var doc struct {
		Keys []map[string]string `json:"keys"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &doc); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(doc.Keys) != 1 {
		t.Fatalf("keys = %d, want 1", len(doc.Keys))
	}
	k := doc.Keys[0]
	if k["kty"] != "OKP" || k["crv"] != "Ed25519" || k["alg"] != "EdDSA" {
		t.Errorf("jwk shape wrong: %+v", k)
	}
	if k["kid"] != ks.KID() {
		t.Errorf("kid mismatch: jwks=%q ks=%q", k["kid"], ks.KID())
	}
	xRaw, err := base64.RawURLEncoding.DecodeString(k["x"])
	if err != nil {
		t.Fatalf("decode x: %v", err)
	}
	if len(xRaw) != ed25519.PublicKeySize {
		t.Fatalf("x len = %d, want %d", len(xRaw), ed25519.PublicKeySize)
	}
	for i, b := range xRaw {
		if b != ks.PublicKey()[i] {
			t.Fatalf("x mismatch at byte %d", i)
		}
	}
}

// TestEncodePrivateKeyPEM_RoundtripsThroughLoad ensures the PEM
// generated by the keystore can re-create an equivalent keystore.
// This is the persistence path: generate once, store as env, redeploy.
func TestEncodePrivateKeyPEM_RoundtripsThroughLoad(t *testing.T) {
	ks1, _ := New("", nil)
	pem, err := ks1.EncodePrivateKeyPEM()
	if err != nil {
		t.Fatalf("EncodePrivateKeyPEM: %v", err)
	}
	ks2, err := New(pem, nil)
	if err != nil {
		t.Fatalf("New(pem): %v", err)
	}
	if ks1.KID() != ks2.KID() {
		t.Fatalf("kid changed across reload: %q vs %q", ks1.KID(), ks2.KID())
	}
	tok, _ := ks1.Sign("u", "user", "leetrank", time.Minute)
	if _, err := ks2.Verify(tok, "leetrank"); err != nil {
		t.Fatalf("ks2 cannot verify ks1 token after PEM roundtrip: %v", err)
	}
}
