source "https://rubygems.org"

ruby ">= 3.2"

gem "sinatra", "~> 4.1"
gem "rackup", "~> 2.2"
gem "puma", "~> 6.5"
gem "redis", "~> 5.3"
gem "mail", "~> 2.8"
gem "json", "~> 2.7"
gem "prometheus-client", "~> 4.2"

group :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
end
